insert into public.employees (slug, name, title, email, photo_url) values
  ('aayush', 'Aayush Talreja', 'Senior Designer', 'aayush.talreja@optimite.net', 'https://raw.githubusercontent.com/aayu5hgit/ESG/refs/heads/main/public/employees/Aayush.png'),
  ('aditya', 'Aditya Tiwari', 'Email Designer Intern', 'aditya.tiwari@optimite.net', 'https://raw.githubusercontent.com/aayu5hgit/ESG/refs/heads/main/public/employees/Aditya.png'),
  ('anamika', 'Anamika Kalwan', 'Head of Content', 'anamika.kalwan@optimite.net', 'https://raw.githubusercontent.com/aayu5hgit/ESG/refs/heads/main/public/employees/Anamika.png'),
  ('arpit', 'Arpit Mehar', 'Content Writer', 'arpit.mehar@optimite.net', 'https://raw.githubusercontent.com/aayu5hgit/ESG/refs/heads/main/public/employees/Arpit.png'),
  ('ayush_agrawal', 'Ayush Agrawal', 'Account Manager', 'ayush.agrawal@optimite.net', 'https://raw.githubusercontent.com/aayu5hgit/ESG/refs/heads/main/public/employees/Ayush.png'),
  ('ayush_maan', 'Ayush Maan', 'Head of Research', 'ayush.maan@optimite.net', 'https://raw.githubusercontent.com/aayu5hgit/ESG/refs/heads/main/public/employees/Ayushmaan.png'),
  ('chhavi', 'Chhavi Singh', 'Client Success Manager', 'chhavi.singh@optimite.net', 'https://raw.githubusercontent.com/aayu5hgit/ESG/refs/heads/main/public/employees/Chhavi.png'),
  ('dishank', 'Dishank Chauhan', 'Client Success Manager Intern', 'dishank.chauhan@optimite.net', 'https://raw.githubusercontent.com/aayu5hgit/ESG/refs/heads/main/public/employees/Dishank.png'),
  ('dhruvi', 'Dhruvi Vithlani', 'Graphic Designer', 'dhruvi.vithlani@optimite.net', 'https://raw.githubusercontent.com/aayu5hgit/ESG/refs/heads/main/public/employees/Dhruvi.png'),
  ('farhana', 'Farhana Nasreen', 'Account Manager', 'farhana.nasreen@optimite.net', 'https://raw.githubusercontent.com/aayu5hgit/ESG/refs/heads/main/public/employees/Farhana.png'),
  ('gaurang', 'Gaurang Nagar', 'Associate - Email Marketing', 'gaurang.nagar@optimite.net', 'https://raw.githubusercontent.com/aayu5hgit/ESG/refs/heads/main/public/employees/Gaurang.png'),
  ('gaurav', 'Gaurav Pandey', 'Graphic Designer', 'gaurav.pandey@optimite.net', 'https://raw.githubusercontent.com/aayu5hgit/ESG/refs/heads/main/public/employees/Gaurav.png'),
  ('harish_parameshwar', 'Harish Parameshwar', 'Founder’s Office Strategy & Ops Lead', 'harish.parameshwar@optimite.net', 'https://raw.githubusercontent.com/aayu5hgit/ESG/refs/heads/main/public/employees/Harish.png'),
  ('harsh', 'Harsh Kumar', 'Head Of Operation', 'harsh.kumar@optimite.net', 'https://raw.githubusercontent.com/aayu5hgit/ESG/refs/heads/main/public/employees/Harsh.png'),
  ('harshita', 'Harshita Prasad', 'Graphic Designer', 'harshita.prasad@optimite.net', 'https://raw.githubusercontent.com/aayu5hgit/ESG/refs/heads/main/public/employees/Harshita.png'),
  ('kanchan', 'Kanchan Yadav', 'Head of Design', 'kanchan.yadav@optimite.net', 'https://raw.githubusercontent.com/aayu5hgit/ESG/refs/heads/main/public/employees/Kanchan.png'),
  ('keyur', 'Keyur Rawal', 'Executive Assistant', 'keyur.rawal@optimite.net', 'https://raw.githubusercontent.com/aayu5hgit/ESG/refs/heads/main/public/employees/Keyur.png'),
  ('kim', 'Kim Longden', 'Email Designer', 'kim.longden@optimite.net', 'https://raw.githubusercontent.com/aayu5hgit/ESG/refs/heads/main/public/employees/Kim.png'),
  ('madhav', 'Madhav Yadav', 'Sales and Marketing', 'madhav.yadav@optimite.net', 'https://raw.githubusercontent.com/aayu5hgit/ESG/refs/heads/main/public/employees/Madhav.png'),
  ('mahima', 'Mahima Joshi', 'Graphic Designer', 'mahima.joshi@optimite.net', 'https://raw.githubusercontent.com/aayu5hgit/ESG/refs/heads/main/public/employees/Mahima.png'),
  ('monika', 'Monika Thapa', 'Account Manager', 'monika.thapa@optimite.net', 'https://raw.githubusercontent.com/aayu5hgit/ESG/refs/heads/main/public/employees/Monica.png'),
  ('nancy', 'Nancy Verma', 'Head of Sales', 'nancy.verma@optimite.net', 'https://raw.githubusercontent.com/aayu5hgit/ESG/refs/heads/main/public/employees/Nancy.png'),
  ('natwar', 'Natwar Singh Rathore', 'Graphic Designer', 'natwar.rathore@optimite.net', 'https://raw.githubusercontent.com/aayu5hgit/ESG/refs/heads/main/public/employees/Natwar.png'),
  ('nishant', 'Nishant Yadav', 'Co-Founder', 'nishant@optimite.net', 'https://raw.githubusercontent.com/aayu5hgit/ESG/refs/heads/main/public/employees/Nishant.png'),
  ('paridhi', 'Paridhi Rastogi', 'Associate-CSM', 'paridhi.rastogi@optimite.net', 'https://raw.githubusercontent.com/aayu5hgit/ESG/refs/heads/main/public/employees/Paridhi.png'),
  ('prachi', 'Prachi Yadav', 'Email Designer', 'prachi.yadav@optimite.net', 'https://raw.githubusercontent.com/aayu5hgit/ESG/refs/heads/main/public/employees/Prachi.png'),
  ('priyanka', 'Priyanka Nandi', 'Graphic Designer', 'priyanka.nandi@optimite.net', 'https://raw.githubusercontent.com/aayu5hgit/ESG/refs/heads/main/public/employees/Priyanka.png'),
  ('raph', 'Raphael Mgbeme', 'Account Manager', 'raphael.mgbeme@optimite.net', 'https://raw.githubusercontent.com/aayu5hgit/ESG/refs/heads/main/public/employees/Raphael.png'),
  ('ratnavi', 'Ratnavi Shetty', 'Account Manager', 'ratnavi.shetty@optimite.net', 'https://raw.githubusercontent.com/aayu5hgit/ESG/refs/heads/main/public/employees/Ratnavi.png'),
  ('santu', 'Santu Kumar', 'Sr. Associate Email Developer', 'santu.kumar@optimite.net', 'https://raw.githubusercontent.com/aayu5hgit/ESG/refs/heads/main/public/employees/Santu.png'),
  ('shaina', 'Shaina Shingari', 'Email Design Intern', 'shaina.shingari@optimite.net', 'https://raw.githubusercontent.com/aayu5hgit/ESG/refs/heads/main/public/employees/Shaina.png'),
  ('shrestha', 'Shrestha Ghosal', 'Content Writer', 'shrestha.ghosal@optimite.net', 'https://raw.githubusercontent.com/aayu5hgit/ESG/refs/heads/main/public/employees/Shrestha.png'),
  ('shyam', 'Shyam Agarwal', 'Head of Operations', 'shyam.agarwal@optimite.net', 'https://raw.githubusercontent.com/aayu5hgit/ESG/refs/heads/main/public/employees/Shyam.png'),
  ('simran', 'Simran Verma', 'HR', 'simran.verma@optimite.net', 'https://raw.githubusercontent.com/aayu5hgit/ESG/refs/heads/main/public/employees/Simran.png'),
  ('sumit', 'Sumit Verma', 'Sr. Associate Email Developer', 'sumit.verma@optimite.net', 'https://raw.githubusercontent.com/aayu5hgit/ESG/refs/heads/main/public/employees/Sumit.png'),
  ('suraj', 'Suraj Nishad', 'Web Developer', 'suraj.nishad@optimite.net', 'https://raw.githubusercontent.com/aayu5hgit/ESG/refs/heads/main/public/employees/Suraj.png'),
  ('sushant', 'Sushant Yadav', 'Co-Founder', 'sushant@optimite.net', 'https://raw.githubusercontent.com/aayu5hgit/ESG/refs/heads/main/public/employees/Sushant.png'),
  ('tanvi', 'Tanvi Sundaram', 'Creative Content Producer', 'tanvi.sundaram@optimite.net', 'https://raw.githubusercontent.com/aayu5hgit/ESG/refs/heads/main/public/employees/Tanvi.png'),
  ('upasana', 'Upasana Barua', 'Graphic Designer', 'upasana.barua@optimite.net', 'https://raw.githubusercontent.com/aayu5hgit/ESG/refs/heads/main/public/employees/Upasana.png'),
  ('vishal', 'Vishal Kumar', '', 'vishal.kumar@optimite.net', 'https://raw.githubusercontent.com/aayu5hgit/ESG/refs/heads/main/public/employees/Vishal.png'),
  ('yashvi', 'Yashvi Sanghvi', 'Chief of Staff', 'yashvi.sanghvi@optimite.net', 'https://raw.githubusercontent.com/aayu5hgit/ESG/refs/heads/main/public/employees/Yashvi.png');
